version: '3.8'

services:

  kafka-primary:
    image: apache/kafka:3.7.0
    container_name: kafka-primary
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-primary:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-primary:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_MS: 30000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 1000
      KAFKA_LOG_SEGMENT_BYTES: 1048576
    volumes:
      - primary_data:/var/lib/kafka/data

  kafka-dr:
    image: apache/kafka:3.7.0
    container_name: kafka-dr
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '2@kafka-dr:29094'
      KAFKA_LISTENERS: 'PLAINTEXT://:9093,CONTROLLER://:29094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-dr:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - dr_data:/var/lib/kafka/data

  mirrormaker2:
    image: saideepthi18/enhanced-mm2:latest
    container_name: mirrormaker2
    depends_on:
      - kafka-primary
      - kafka-dr
    volumes:
      - ./mm2.properties:/opt/kafka/config/mm2.properties
    command: /opt/kafka/config/mm2.properties
    restart: on-failure

  commit-log-producer:
    image: saideepthi18/commit-log-producer:latest
    container_name: commit-log-producer
    environment:
      KAFKA_BROKER: kafka-primary:9092
      TOPIC_NAME: commit-log

volumes:
  primary_data:
  dr_data: